Proxy to jeffseemann.test in local development
SquaredLabs/Jeff-Website pull request #5
Opened 2018-05-05 21:24 UTC by gluxon

I had to replace the call to url.format since it took protocol,
hostname, and port as separate arguments. An alternative that just joins
two paths makes envrionment setup a bit easier. (url.resolve)

So REACT_APP_DIRECTUS_PROTOCOL and REACT_APP_DIRECTUS_HOSTNAME are
deprecated in favor of REACT_APP_DIRECTUS_ENDPOINT, which is more
flexible.

These changes assume the site is setup at jeffseemann.test. I don't
believe there's a way at the moment to get package.json to use an
environment variable while proxying.

2018-05-05 21:29 UTC, gluxon commented
This build will fail until I change the environment variables on drone. I'll do that after it's merged since doing it prematurely will break develop's builds.

2018-05-05 21:52 UTC, qvissak commented on README.md
>  Change the line `server_name localhost;` to `server_name jeffwebsite.test;` since you'll probably be using localhost for something else.
You missed one ;-)

2018-05-05 21:53 UTC, qvissak requested changes

2018-05-05 21:53 UTC, qvissak commented on README.md
>  Change the line `server_name localhost;` to `server_name jeffwebsite.test;` since you'll probably be using localhost for something else.
You missed one ;-)

2018-05-05 22:25 UTC, qvissak approved these changes

2018-05-05 22:26 UTC, merged

2018-05-07 15:59 UTC, CourtAW commented
all set! thanks guys 👍